[package]
name = "sokoban-rs"
version = "1.1.0"
authors = ["SÃ©bastien Watteau"]
description = "An implementation of Sokoban in Rust"
repository = "https://github.com/swatteau/sokoban-rs"
readme = "README.adoc"
keywords = ["game", "sokoban"]
license = "Apache-2.0"

[dependencies]
bitflags = "0.6.0"
sdl2 = "0.19.0"
sdl2_image = "0.19.0"
sdl2_ttf = "0.19.0"
xml-rs = "0.2.2"
clap = { version = "1.5.5", features = ["yaml"] }

